name: Sync Upstream
on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:   

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    name: Sync latest commits from upstream repo
    # This line below fixes the warning you're seeing:
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout target repo
      uses: actions/checkout@v4
      with:
        ref: master 

    - name: Sync upstream changes
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: master
        target_repo_token: ${{ secrets.GITHUB_TOKEN }}
        upstream_sync_repo: solutiojoel/joomla-mcp
        upstream_sync_branch: master
        test_mode: false
